"""
Assignment 2: submission self-check.

Runs the same checks locally and on GitHub, so there is exactly one
definition of "does this submission work" and no drift between them:

    uv run python check.py

By default it does NOT train anything. It checks what a grader needs to be
true of your submitted repo:

1. Your Roboflow API key is findable and Roboflow accepts it.
2. weights/ holds a model that actually loads.
3. Your app launches and responds, serving those weights.

Training is not re-run because a real finetune does not fit in a check. If you
also want to confirm your training stage runs end to end, do it yourself:

    uv run python check.py --train

That runs main.py train first, with no time limit. Run it on a machine where
training is practical.

A non-zero exit means something a grader will also hit. Do not edit this file
to make it pass. Fix what it is pointing at.

Set APP_PORT if your app does not launch on Gradio's default 7860.
"""

import argparse
import os
import signal
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path

from api_key import masked, resolve_api_key, verify

ROOT = Path(__file__).resolve().parent
WEIGHTS_DIR = ROOT / "weights"
APP_PORT = int(os.environ.get("APP_PORT", "7860"))
APP_STARTUP_TIMEOUT = int(os.environ.get("APP_STARTUP_TIMEOUT", "120"))


def fail(message: str) -> None:
    print(f"\nFAIL: {message}", file=sys.stderr)
    sys.exit(1)


TOTAL_STEPS = 3


def step(n: int, title: str) -> None:
    print(f"\n=== {n}/{TOTAL_STEPS}  {title} ".ljust(72, "=") + "\n", flush=True)


def _tail(path: Path, lines: int = 20) -> str:
    """Last few lines of the app's output, to show why it failed."""
    try:
        tail = path.read_text(errors="replace").splitlines()[-lines:]
    except OSError:
        return ""
    return "\n  --- app output ---\n" + "\n".join(f"  {line}" for line in tail)


def committed_weights() -> list[Path]:
    if not WEIGHTS_DIR.is_dir():
        return []
    return sorted(p for p in WEIGHTS_DIR.rglob("*.pt") if p.is_file())


def stop_process_tree(proc: subprocess.Popen) -> None:
    """Kill the app and everything it spawned.

    `main.py app` runs your app as a *child* of itself, so terminating the
    process we launched would leave the real Gradio process alive, still
    holding the port and the inherited output stream. In CI that hangs the job
    until it times out. Signal the whole process group instead.
    """
    if proc.poll() is not None:
        return
    try:
        if os.name == "posix":
            os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
        else:
            subprocess.run(
                ["taskkill", "/F", "/T", "/PID", str(proc.pid)],
                capture_output=True,
                check=False,
            )
    except (ProcessLookupError, PermissionError, OSError):
        proc.terminate()
    try:
        proc.wait(timeout=15)
    except subprocess.TimeoutExpired:
        try:
            if os.name == "posix":
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            else:
                proc.kill()
        except (ProcessLookupError, PermissionError, OSError):
            pass


def main() -> None:
    global TOTAL_STEPS
    parser = argparse.ArgumentParser(description="Check this submission.")
    parser.add_argument(
        "--train",
        action="store_true",
        help="also run main.py train first (no time limit; needs a machine where "
             "training is practical)",
    )
    args = parser.parse_args()
    TOTAL_STEPS = 4 if args.train else 3
    n = 0

    n += 1
    step(n, "Checking your Roboflow API key")
    key, source = resolve_api_key()
    if not key:
        fail(
            "No Roboflow API key found.\n"
            "  Locally  : copy .env.example to .env and paste your key in.\n"
            "  On GitHub: add it under Settings > Secrets and variables > Actions\n"
            "             on YOUR fork, named ROBOFLOW_API_KEY.\n"
            "  Then run `uv run python api_key.py` on its own to check it."
        )
    print(f"Found a key in {source}: {masked(key)}")
    os.environ["ROBOFLOW_API_KEY"] = key
    works, detail = verify(key)
    if not works:
        fail(
            f"That key did not work: {detail}\n"
            "  An unusable key produces an unreadable Roboflow error much further\n"
            "  down, which is why this is checked first."
        )
    print(f"Key works. Workspace: {detail}")

    if args.train:
        n += 1
        step(n, "Running your training stage (main.py train)")
        started = time.time()
        result = subprocess.run([sys.executable, "main.py", "train"], cwd=ROOT)
        if result.returncode != 0:
            fail(f"`main.py train` exited with code {result.returncode}.")
        print(f"\nTraining stage completed in {time.time() - started:.1f}s.")

    n += 1
    step(n, "Loading your committed weights")
    found = committed_weights()
    if not found:
        fail(
            "No .pt file in weights/.\n"
            "  Commit the weights your real training run produced. They are what\n"
            "  your app loads, and without them nobody can run your submission."
        )
    try:
        from ultralytics import YOLO
    except ImportError as error:
        fail(f"Could not import ultralytics: {error}")
    for weight in found:
        try:
            model = YOLO(str(weight))
            names = getattr(model, "names", None) or {}
        except Exception as error:  # noqa: BLE001 - any load failure is the finding
            fail(
                f"{weight.relative_to(ROOT)} did not load: "
                f"{type(error).__name__}: {error}"
            )
        classes = ", ".join(str(v) for v in list(dict(names).values())[:8])
        more = "..." if len(names) > 8 else ""
        print(
            f"{weight.relative_to(ROOT)} loads. "
            f"{len(names)} class(es): {classes}{more}"
        )

    n += 1
    step(n, f"Launching your app and checking it responds on port {APP_PORT}")
    url = f"http://127.0.0.1:{APP_PORT}"
    log_path = Path(tempfile.gettempdir()) / "assignment2-app.log"

    # Give the app its own process group, and send its output to a file rather
    # than inheriting ours: an app that outlives this script must not be able to
    # hold our stdout open, or whatever is reading us waits forever.
    spawn_kwargs: dict = (
        {"start_new_session": True}
        if os.name == "posix"
        else {"creationflags": subprocess.CREATE_NEW_PROCESS_GROUP}
    )

    with log_path.open("w") as log:
        app = subprocess.Popen(
            [sys.executable, "main.py", "app"],
            cwd=ROOT,
            stdout=log,
            stderr=subprocess.STDOUT,
            **spawn_kwargs,
        )
        try:
            deadline = time.time() + APP_STARTUP_TIMEOUT
            while True:
                if app.poll() is not None:
                    fail(
                        f"`main.py app` exited with code {app.returncode} before it "
                        f"ever responded.\n  Your app must build a Gradio `demo` and "
                        f"call .launch(), and must not train anything.\n"
                        + _tail(log_path)
                    )
                try:
                    with urllib.request.urlopen(url, timeout=3) as response:
                        if response.status == 200:
                            break
                except (urllib.error.URLError, OSError, TimeoutError):
                    pass
                if time.time() >= deadline:
                    fail(
                        f"App process is running but never responded on {url} within "
                        f"{APP_STARTUP_TIMEOUT}s.\n  If your app launches on a "
                        f"different port, set APP_PORT.\n" + _tail(log_path)
                    )
                time.sleep(2)
            print(f"App responded on {url}.")
        finally:
            stop_process_tree(app)

    print("\n" + "=" * 72)
    print("All checks passed.")
    print("=" * 72)


if __name__ == "__main__":
    main()
